services:
    _defaults:
        public: true

    CoreShop\Bundle\ThemeBundle\Collector\ThemeCollector:
        arguments:
            - '@CoreShop\Bundle\ThemeBundle\Service\ActiveThemeInterface'
            - '@coreshop.theme.resolver'
        tags:
            - { name: data_collector, template: '@CoreShopTheme/Collector/theme.html.twig', id: coreshop.theme_collector }
